name: 'publish'
on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            arch: 'arm64'
            args: '--target aarch64-apple-darwin'
            folder: 'aarch64-apple-darwin'
          - platform: 'macos-latest'
            arch: 'amd64'
            args: '--target x86_64-apple-darwin'
            folder: 'x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            arch: 'amd64'
            args: ''
            folder: ''
          - platform: 'windows-latest'
            arch: 'amd64'
            args: ''
            folder: ''
    runs-on: ${{ matrix.platform }}
    env:
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Install dependencies with Bun
        run: bun install
      - name: Build Tauri app
        run: bun run tauri build ${{ matrix.args }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-${{ matrix.platform }}-${{ matrix.arch }}
          path: ${{ matrix.folder == '' && 'src-tauri/target/release/bundle' || format('src-tauri/target/{0}/release/bundle', matrix.folder) }}
          retention-days: 5  # Optional: specify how long to keep the artifacts
          compression-level: 6  # Optional: specify compression level (0-9)